package org.java;

public class Exception {
public static void main(String[] args) {
	
	System.out.println(1+9);
	
	try {
		
		String s = "Masha";
		char x = s.charAt(2);
		System.out.println(x);
		System.out.println(4/0);
	}
	
	finally {
		System.out.println("End");
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
//	 catch (StringIndexOutOfBoundsException e) {
//			e.printStackTrace();
//		}
//	catch (ArithmeticException e) {
//		System.out.println("Don't divide by Zero");
//	}
//	finally {
//		System.out.println("To Be Continued");
//	}
//	try {
//		String s = null;
//		char y = s.charAt(2);
//		System.out.println(y);
//	} 
//	catch (NullPointerException e) {
//		e.printStackTrace();
//	}
//	
	
	
	
	
	
	
	
	
	
	
}
}
